### PR TITLE
[Demo] Make sidenav animate on toggle. Integrate app-wide breakpoints.

### PR DESCRIPTION
**Pull request by BrianSipple**
This PR addresses #36, and ideally would go in just after PR #37. 

I added `ember-responsive` to the project in order to control breakpoints across the application. I also made the sidenav toggleable and have it setup to animate side-by-side with the main page content. (Special bonus: It's even [swipeable on touch devices](https://github.com/elwayman02/ember-data-twitch/pull/38/files#diff-b2c258511c7d03253e9161d5855362baR59)!)

(For visual reference, I have the [demo for the latest changes](http://www.sipple.io/ember-data-twitch/) deployed to the `gh-pages` branch of my own fork.)

I'm still not completely sold on a few things, such as the exact breakpoint dimensions or the full coloring of the sidenav panel. But, I'm figuring those are things we can tinker with pretty straightforwardly at just about any time -- the changes here will at least go a long way to help us build out the rest of the demo with responsive breakpoints in mind.

### CODE REVIEW

**Comment by elwayman02** [comment]
The demo looks off on desktop Chrome:

dummy

dummy

**Comment by BrianSipple** [comment]
Ugh, yeah, styles for positioning icons were a bit off when I pushed the demo. It should be fixed now.

**Comment by elwayman02** [comment]
Needs rebase

**Comment by BrianSipple** [comment]
Updated

**Comment by BrianSipple** [comment]
@elwayman02 Friendly ping. Just want to make sure [everything looks good](http://www.sipple.io/ember-data-twitch/) in someone else's environment before merging anything.

**Comment by elwayman02** [comment]
Sorry thought I already responded! Looks fine on desktop, on mobile the
sidenav is maybe a little too wide... It takes up about 90% of the screen
width on my Nexus 6P.

**Comment by BrianSipple** [comment]
@elwayman02 Sorry for leaving this hanging for so long! I tweaked the width of the sidenav down to 260px, which factors out to about 60% of Nexus 6P screen width (412px), but still leaves plenty of room for each route/page title.

**Pull request merged**
